### ISSUE TITLE
Game not be working?

### ISSUE THREAD

**Issue by quackduck** [hackclub/www-assemble#31]
button not do things

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/38882631/176715068-cdf6b53e-5840-4328-8e7b-3cfdb8f34509.png">

**Comment by Merlin04** [comment]
`Uncaught SyntaxError: unexpected token: ']'           [assemble.hackclub.com:77:54956](https://assemble.hackclub.com/)`

Uh that's weird, will work on a pr to fix

**Comment by Merlin04** [comment]
I think @YodaLightsabr 's reformatting broke it, no idea why - will try to disable prettier for that

**Comment by YodaLightsabr** [comment]
@Merlin04 I apologize! I ran prettier mostly to fix my 4 spaces > 2 spaces, but I didn't think it would break anything.
